# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import broker_api_pb2 as broker__api__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in broker_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountInfoServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAccountInfoChangedStream = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.AccountInfoServiceExternal/getAccountInfoChangedStream',
                request_serializer=broker__api__pb2.PBAccountInfoChangedRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBAccountInfoChangedStreamResponseExternal.FromString,
                _registered_method=True)


class AccountInfoServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAccountInfoChangedStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountInfoServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAccountInfoChangedStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getAccountInfoChangedStream,
                    request_deserializer=broker__api__pb2.PBAccountInfoChangedRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBAccountInfoChangedStreamResponseExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.AccountInfoServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.AccountInfoServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountInfoServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAccountInfoChangedStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.AccountInfoServiceExternal/getAccountInfoChangedStream',
            broker__api__pb2.PBAccountInfoChangedRequestExternal.SerializeToString,
            broker__api__pb2.PBAccountInfoChangedStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PositionsServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getClientPositionsStream = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.PositionsServiceExternal/getClientPositionsStream',
                request_serializer=broker__api__pb2.PBClientPositionRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBPositionStreamResponseExternal.FromString,
                _registered_method=True)
        self.getOpenPositionsStreamByGroupsOrLogins = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.PositionsServiceExternal/getOpenPositionsStreamByGroupsOrLogins',
                request_serializer=broker__api__pb2.PBOpenPositionRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBOpenPositionsStreamResponseExternal.FromString,
                _registered_method=True)


class PositionsServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getClientPositionsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getOpenPositionsStreamByGroupsOrLogins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PositionsServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getClientPositionsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getClientPositionsStream,
                    request_deserializer=broker__api__pb2.PBClientPositionRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBPositionStreamResponseExternal.SerializeToString,
            ),
            'getOpenPositionsStreamByGroupsOrLogins': grpc.unary_stream_rpc_method_handler(
                    servicer.getOpenPositionsStreamByGroupsOrLogins,
                    request_deserializer=broker__api__pb2.PBOpenPositionRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBOpenPositionsStreamResponseExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.PositionsServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.PositionsServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PositionsServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getClientPositionsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.PositionsServiceExternal/getClientPositionsStream',
            broker__api__pb2.PBClientPositionRequestExternal.SerializeToString,
            broker__api__pb2.PBPositionStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getOpenPositionsStreamByGroupsOrLogins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.PositionsServiceExternal/getOpenPositionsStreamByGroupsOrLogins',
            broker__api__pb2.PBOpenPositionRequestExternal.SerializeToString,
            broker__api__pb2.PBOpenPositionsStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LedgerServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLedgersStreamByLogin = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.LedgerServiceExternal/getLedgersStreamByLogin',
                request_serializer=broker__api__pb2.PBLedgerRequestByLoginExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBLedgerStreamResponseExternal.FromString,
                _registered_method=True)
        self.getLedgersStreamByGroupsOrLogins = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.LedgerServiceExternal/getLedgersStreamByGroupsOrLogins',
                request_serializer=broker__api__pb2.PBLedgersRequestByGroupsOrLoginsExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBLedgersStreamResponseExternal.FromString,
                _registered_method=True)


class LedgerServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLedgersStreamByLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLedgersStreamByGroupsOrLogins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedgerServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLedgersStreamByLogin': grpc.unary_stream_rpc_method_handler(
                    servicer.getLedgersStreamByLogin,
                    request_deserializer=broker__api__pb2.PBLedgerRequestByLoginExternal.FromString,
                    response_serializer=broker__api__pb2.PBLedgerStreamResponseExternal.SerializeToString,
            ),
            'getLedgersStreamByGroupsOrLogins': grpc.unary_stream_rpc_method_handler(
                    servicer.getLedgersStreamByGroupsOrLogins,
                    request_deserializer=broker__api__pb2.PBLedgersRequestByGroupsOrLoginsExternal.FromString,
                    response_serializer=broker__api__pb2.PBLedgersStreamResponseExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.LedgerServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.LedgerServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LedgerServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLedgersStreamByLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.LedgerServiceExternal/getLedgersStreamByLogin',
            broker__api__pb2.PBLedgerRequestByLoginExternal.SerializeToString,
            broker__api__pb2.PBLedgerStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getLedgersStreamByGroupsOrLogins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.LedgerServiceExternal/getLedgersStreamByGroupsOrLogins',
            broker__api__pb2.PBLedgersRequestByGroupsOrLoginsExternal.SerializeToString,
            broker__api__pb2.PBLedgersStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrderServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getOrdersUpdateStreamByGroupsOrLogins = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.OrderServiceExternal/getOrdersUpdateStreamByGroupsOrLogins',
                request_serializer=broker__api__pb2.PBOrdersUpdateStreamRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBOrdersUpdateStreamResponseExternal.FromString,
                _registered_method=True)


class OrderServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getOrdersUpdateStreamByGroupsOrLogins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getOrdersUpdateStreamByGroupsOrLogins': grpc.unary_stream_rpc_method_handler(
                    servicer.getOrdersUpdateStreamByGroupsOrLogins,
                    request_deserializer=broker__api__pb2.PBOrdersUpdateStreamRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBOrdersUpdateStreamResponseExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.OrderServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.OrderServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getOrdersUpdateStreamByGroupsOrLogins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.OrderServiceExternal/getOrdersUpdateStreamByGroupsOrLogins',
            broker__api__pb2.PBOrdersUpdateStreamRequestExternal.SerializeToString,
            broker__api__pb2.PBOrdersUpdateStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QuotationsServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getQuotationsWithMarkupStream = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.QuotationsServiceExternal/getQuotationsWithMarkupStream',
                request_serializer=broker__api__pb2.PBQuotationsWithMarkupStreamRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBQuotationSimpleExternal.FromString,
                _registered_method=True)


class QuotationsServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getQuotationsWithMarkupStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuotationsServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getQuotationsWithMarkupStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getQuotationsWithMarkupStream,
                    request_deserializer=broker__api__pb2.PBQuotationsWithMarkupStreamRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBQuotationSimpleExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.QuotationsServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.QuotationsServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuotationsServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getQuotationsWithMarkupStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.QuotationsServiceExternal/getQuotationsWithMarkupStream',
            broker__api__pb2.PBQuotationsWithMarkupStreamRequestExternal.SerializeToString,
            broker__api__pb2.PBQuotationSimpleExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GroupServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getGroupChangesStream = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.GroupServiceExternal/getGroupChangesStream',
                request_serializer=broker__api__pb2.PBGroupChangeStreamRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBGroupChangeStreamResponseExternal.FromString,
                _registered_method=True)


class GroupServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getGroupChangesStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroupServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getGroupChangesStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getGroupChangesStream,
                    request_deserializer=broker__api__pb2.PBGroupChangeStreamRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBGroupChangeStreamResponseExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.GroupServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.GroupServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroupServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getGroupChangesStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.GroupServiceExternal/getGroupChangesStream',
            broker__api__pb2.PBGroupChangeStreamRequestExternal.SerializeToString,
            broker__api__pb2.PBGroupChangeStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TradingEventsServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTradingEventsStream = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.TradingEventsServiceExternal/getTradingEventsStream',
                request_serializer=broker__api__pb2.PBTradingEventsStreamRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBTradingEventsStreamResponseExternal.FromString,
                _registered_method=True)


class TradingEventsServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTradingEventsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingEventsServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTradingEventsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getTradingEventsStream,
                    request_deserializer=broker__api__pb2.PBTradingEventsStreamRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBTradingEventsStreamResponseExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.TradingEventsServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.TradingEventsServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingEventsServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTradingEventsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.TradingEventsServiceExternal/getTradingEventsStream',
            broker__api__pb2.PBTradingEventsStreamRequestExternal.SerializeToString,
            broker__api__pb2.PBTradingEventsStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SymbolsServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSymbolsChangedStream = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.SymbolsServiceExternal/getSymbolsChangedStream',
                request_serializer=broker__api__pb2.PBSymbolChangedRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBSymbolChangedStreamResponseExternal.FromString,
                _registered_method=True)


class SymbolsServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSymbolsChangedStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SymbolsServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSymbolsChangedStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getSymbolsChangedStream,
                    request_deserializer=broker__api__pb2.PBSymbolChangedRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBSymbolChangedStreamResponseExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.SymbolsServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.SymbolsServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SymbolsServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSymbolsChangedStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.SymbolsServiceExternal/getSymbolsChangedStream',
            broker__api__pb2.PBSymbolChangedRequestExternal.SerializeToString,
            broker__api__pb2.PBSymbolChangedStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EquityServiceExternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getClientEquityStream = channel.unary_stream(
                '/com.matchtrade.broker_api.grpc.EquityServiceExternal/getClientEquityStream',
                request_serializer=broker__api__pb2.PBEquityRequestExternal.SerializeToString,
                response_deserializer=broker__api__pb2.PBEquityStreamResponseExternal.FromString,
                _registered_method=True)


class EquityServiceExternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getClientEquityStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EquityServiceExternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getClientEquityStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getClientEquityStream,
                    request_deserializer=broker__api__pb2.PBEquityRequestExternal.FromString,
                    response_serializer=broker__api__pb2.PBEquityStreamResponseExternal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.matchtrade.broker_api.grpc.EquityServiceExternal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.matchtrade.broker_api.grpc.EquityServiceExternal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EquityServiceExternal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getClientEquityStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.matchtrade.broker_api.grpc.EquityServiceExternal/getClientEquityStream',
            broker__api__pb2.PBEquityRequestExternal.SerializeToString,
            broker__api__pb2.PBEquityStreamResponseExternal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
